config_diagnostics =1
extensions = default_skid_akid

[ default_skid_akid ]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:nonss,issuer:nonss

[req]
default_algorithm = rsa
default_bits = 4096
prompt = no
default_md = sha256
x509_extensions = v3_authority
distinguished_name = dn

[dn]
C = "LV"
ST = "Riga"
L = "Riga"
O = "University of Latvia"
OU = "Student"
CN = "Converter authority"

[ v3_authority ]
subjectKeyIdentifier = hash
extendedKeyUsage = critical, serverAuth, clientAuth
basicConstraints = CA:true
keyUsage = cRLSign, keyCertSign, digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment, keyAgreement, keyCertSign, cRLSign

[ v3_converter1 ]
basicConstraints = critical,CA:false
keyUsage = nonRepudiation, digitalSignature
extendedKeyUsage = critical, clientAuth, serverAuth
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always
subjectAltName = @converter1-alt-names

[ v3_converter2 ]
basicConstraints = critical,CA:false
keyUsage = nonRepudiation, digitalSignature
extendedKeyUsage = critical, clientAuth, serverAuth
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always
subjectAltName = @converter2-alt-names

[ v3_etsi_server1 ]
basicConstraints = critical,CA:false
keyUsage = nonRepudiation, digitalSignature
extendedKeyUsage = critical, serverAuth
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always
subjectAltName = @etsi_server1-alt-names

[ v3_etsi_server2 ]
basicConstraints = critical,CA:false
keyUsage = nonRepudiation, digitalSignature
extendedKeyUsage = critical, serverAuth
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always
subjectAltName = @etsi_server2-alt-names


[ converter1-alt-names ]
DNS.1 = converter1
DNS.2 = localhost

[ converter2-alt-names ]
DNS.1 = converter2
DNS.2 = localhost

[ etsi_server1-alt-names ]
DNS.1 = etsi_server1
DNS.2 = localhost

[ etsi_server2-alt-names ]
DNS.1 = etsi_server2
DNS.2 = localhost

[ sae2-alt-names ]
DNS.1 = bob2
DNS.2 = localhost

[ sae1-alt-names ]
DNS.1 = bob1
DNS.2 = localhost